name: Release

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      dry-run:
        description: "Dry run (no actual release)"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for conventional commits
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Validate code
        run: |
          deno check
          deno test --allow-all
          deno lint

      - name: Build binaries
        run: |
          set -euo pipefail
          mkdir -p dist
          deno compile --allow-all --target x86_64-unknown-linux-gnu --output dist/claude-cleaner-linux-x64 src/main.ts
          deno compile --allow-all --target aarch64-unknown-linux-gnu --output dist/claude-cleaner-linux-arm64 src/main.ts
          deno compile --allow-all --target x86_64-apple-darwin --output dist/claude-cleaner-macos-x64 src/main.ts
          deno compile --allow-all --target aarch64-apple-darwin --output dist/claude-cleaner-macos-arm64 src/main.ts
          deno compile --allow-all --target x86_64-pc-windows-msvc --output dist/claude-cleaner-windows-x64.exe src/main.ts

      - name: Run semantic-release (dry-run)
        if: ${{ inputs.dry-run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run

      - name: Run semantic-release
        if: ${{ !inputs.dry-run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
